#https://trello.com/1/appKey/generate
#https://trello.com/1/connect?key=<appKey>&name=OpenShift&response_type=token&scope=read,write,account
#https://trello.com/1/connect?key=<appKey>&name=OpenShift&response_type=token&scope=read,write,account&expiration=never
---
:consumer_key: <consumer_key>
:consumer_secret: <consumer_secret>
:oauth_token: <oauth_token>
:max_lists_per_board: 26
:default_product: product1
:other_products:
  - product2
  - product3
:product_order:
  - product1
  - product2
  - product3
:teams:
  :team1:
    :boards:
      :team1_board1: <team1_board1_id>
      :team1_board2: <team1_board2_id>
    :dependent_work_boards:
      <team1_documentation_board_id>:
        :label: documentation
        :new_list_name: New
        :card_name_prefix: Team1-Document
        :card_desc_prefix: Corresponding Development Card
        :task_reminder_text: Update this card with team1-specific details about what needs to be documented.
  :team2:
    :boards:
      :team2_board: <team2_board_id>
:roadmap_id: <roadmap_id>
:public_roadmap_id: <public_roadmap_id>
:dependent_work_boards:
  <documentation_board_id>:
    :label: documentation
    :new_list_name: New
    :card_name_prefix: Document
    :card_desc_prefix: Corresponding Development Card
    :task_reminder_text: Update this card (in the description or in a comment) with details about what needs to be documented.
  <other_board_id>:
    :label: other_work
    :new_list_name: New
    :card_name_prefix: Other
    :card_desc_prefix: Corresponding Development Card
    :task_reminder_text: Update this card (in the description or in a comment) with details about any additional work required
:organization_id: <organication short name>
:organization_name: <organization display name>
:roadmap_board_lists:
 - 'New'
 - 'Epic Backlog'
 - 'Clusters'
:sprint_length_in_weeks: 3
:sprint_start_day: monday
:sprint_end_day: friday
:logo: <logo url>
:archive_path: <archive path>
